# Generated by Django 6.0.4 on 2026-07-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField()),
                ('strengths', models.JSONField()),
                ('weakness', models.JSONField()),
                ('missing_skills', models.JSONField()),
                ('project_analysis', models.JSONField()),
                ('suggested_roles', models.JSONField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.profile')),
            ],
        ),
    ]
