# Generated by Django 6.0.4 on 2026-07-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='analysis',
            name='QuestionSet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.questionanswer'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='real_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.resume'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='user_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai.analysis')),
                ('questionanswerset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.questionanswer')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.resume')),
            ],
        ),
    ]
